### ISSUE TITLE
der_derive: could not compile with syn v2.0.73

### ISSUE THREAD

**Issue by yayanyang** [RustCrypto/formats#1471]
error[E0502]: cannot borrow `generics.params` as mutable because it is also borrowed as immutable

--> sequence.rs:61:29
   |
57 |           let lifetime = generics
   |                          --------
   |                          |
   |  ________________________immutable borrow occurs here
   | |
58 | |             .lifetimes()
   | |________________________- a temporary with access to the immutable borrow is created here ...
...
61 |               .unwrap_or_else(|| {
   |                               ^^ mutable borrow occurs here
62 |                   let lt = default_lifetime();
63 | /                 generics
64 | |                     .params
   | |___________________________- second borrow occurs due to use of `generics.params` in closure
...
67 |               });
   |                 - ... and the immutable borrow might be used here, when that temporary is dropped and runs the destructor for type `impl Iterator<Item = &LifetimeParam>`

**Comment by foxyseta** [comment]
Same here.

**Comment by yayanyang** [comment]
> Same here.

Set syn="=2.0.72"

**Comment by tarcieri** [comment]
What changed in `syn`?

**Comment by tarcieri** [comment]
Opened an upstream issue in `syn` here: https://github.com/dtolnay/syn/issues/1718
