### ISSUE TITLE
Pkcs8 PrivateKeyInfo is no longer "useful" from version 0.11.0

### ISSUE THREAD

**Issue by Firstyear** [RustCrypto/formats#2402]
As of 0.11.0 the type signature of PrivateKeyInfo has change to:

```
pub struct PrivateKeyInfo<Params, Key, PubKey> {
 ...
```

The problem with this is that these generic parameters can't be satisfied without pre-knowledge of the key in question. Consider:

```
let der = // some private key bytes.

let priv_key_info = PrivateKeyInfo::try_from(ecdsa_priv_key_der.as_bytes()).unwrap();
```

This can no longer be satisfied due to:

```
error[E0284]: type annotations needed for `PrivateKeyInfo<_, _, _>`
    --> src/lib.rs:1055:13
     |
1055 |         let priv_key_info = PrivateKeyInfo::try_from(ecdsa_priv_key_der.as_bytes())
     |             ^^^^^^^^^^^^^   -------------- type must be known at this point
     |
     = note: cannot satisfy `<_ as der::Decode<'_>>::Error == der::Error`
     = note: required for `PrivateKeyInfo<_, _, _>` to implement `TryFrom<&[u8]>`
help: consider giving `priv_key_info` an explicit type, where the type for type parameter `Params` is specified
     |
1055 |         let priv_key_info: PrivateKeyInfo<Params, Key, PubKey> = PrivateKeyInfo::try_from(ecdsa_priv_key_der.as_bytes())
     |                          +++++++++++++++++++++++++++++++++++++

```

This means that from some input DER, it is not possible to use PrivateKeyInfo to decode the PKCS8 structure and then understand the key contained within.

Previously this worked with 0.10 which did not have enforced generics on PrivateKeyInfo, so I would consider this a regression: 

https://docs.rs/pkcs8/0.10.2/pkcs8/struct.PrivateKeyInfo.html

**Comment by dishmaker** [comment]
[PrivateKeyInfoRef](https://docs.rs/pkcs8/0.11.0/pkcs8/type.PrivateKeyInfoRef.html) and [PrivateKeyInfoOwned](https://docs.rs/pkcs8/0.11.0/pkcs8/type.PrivateKeyInfoOwned.html) should be used

**Comment by tarcieri** [comment]
Yeah, `PrivateKeyInfoRef` is effectively equivalent to the old `PrivateKeyInfo` before the generic parameters were added.

**Comment by Firstyear** [comment]
I think that there could have been better upgrade guidance here - either a deprecation warning, or documentation on PrivateKeyInfo to tell people about the change.

**Comment by tarcieri** [comment]
@Firstyear deprecations don't really work for this situation as we effectively repurposed `PrivateKeyInfo` as the generic type. We can't deprecate it because it's a useful and important part of the API still.

We can improve documentation and the CHANGELOG though if that helps.

**Comment by Firstyear** [comment]
I think it is really needed, as I wasn't able to solve this or find the new type without opening an issue.
